### ISSUE TITLE
UIImage support for UIBarButtonItem for DismissButtonConfig

### ISSUE THREAD

**Issue by psartzetakis** [jessesquires/PresenterKit#22]
Hi, 😀
I was thinking that it might be a good feature if there was a way to set an image for the  `UIBarButtonItem` through the `DismissButtonConfig`. 
What do you think ? 🤔

**Comment by jessesquires** [comment]
Seems reasonable 👍 

We could add a `.image(UIImage)` case to the `Text` enum:
https://github.com/jessesquires/PresenterKit/blob/develop/Source/DismissButtonConfig.swift#L70-L77

We should probably rename it from `Text` to something else... 🤔

**Comment by jessesquires** [comment]
Renaming `enum Text` would be a breaking change though 😢

**Comment by psartzetakis** [comment]
Would you recommend a different approach in order to avoid renaming `enum Text` ?

**Comment by jessesquires** [comment]
@psartzetakis - Hm... probably not. I can't really thing of a better way to do this. 

It's not a big deal. 😄 

However, it would be nice include more changes for the `4.0` release.

**Comment by psartzetakis** [comment]
> However, it would be nice include more changes for the 4.0 release.

@jessesquires I have a couple of ideas..🤔.
However I believe it would be better to open separate issues so we can discuss them separately..  😀

**Comment by jessesquires** [comment]
> However I believe it would be better to open separate issues so we can discuss them separately.. 

Definitely! 💯 👍
