### ISSUE TITLE
Typed View Controllers from storyboard

### ISSUE THREAD

**Issue by psartzetakis** [jessesquires/PresenterKit#25]
Hi,😀
I have introduced something that personally annoys me, if you find that interesting and you believe that we can include a solution on that issue through `PresenterKit` we can discuss it further.

### The problem

When you bring view controllers from the storyboard usually you do something like that: 
```swift
let colorViewController = self.storyboard?.instantiateViewController(withIdentifier: "identifier") as! ColorViewController
```
The thing that I don't like is that part:
```swift
as! ColorViewController
or
as? ColorViewController
```
### A suggestion
I believe that it would be much nicer to wrap this functionality into something nicer. Perhaps something like:
```swift
extension UIStoryboard {
    func instatiate<T: UIViewController>(type: T.Type, with identifier: String) -> T {
        return instantiateViewController(withIdentifier: identifier) as! T
    }
}
```
As a result we could do something like that:
```swift
let colorViewController = storyboard?.instatiate(type: ColorViewController.self, with: "identifier")
```
### A different suggestion (not that good though..)

**Note**: - personally I use most of the times as identifier the same name as the class name, so it would suit me something like that:
```swift
extension UIStoryboard {
    func instatiate<T: UIViewController>(type: T.Type, identifier: String? = nil) -> T {
        let identifier = identifier ?? "\(type.self)"
        return instantiateViewController(withIdentifier: identifier) as! T
    }
}
```
So I can use it like that:
```swift
let colorViewController = storyboard?.instatiate(type: ColorViewController.self)
```
**But:** I don't thing that could be a good idea since it can be misleading ..

What do you think?

**Comment by jessesquires** [comment]
Thanks @psartzetakis ! 😄 

Sounds cool to me, but it's probably out-of-scope for *this* library, which is focused on presentation.

I think this would fix better in @alisoftware's https://github.com/AliSoftware/Reusable

He has something similar to this: 
https://github.com/AliSoftware/Reusable/blob/master/Sources/Storyboard/StoryboardSceneBased.swift

But I like what you've proposed a lot. 💯

**Comment by psartzetakis** [comment]
@jessesquires  Thanks for the feedback! 😄
