### ISSUE TITLE
How to change popoverViewController size

### ISSUE THREAD

**Issue by blackchena** [jessesquires/PresenterKit#32]
set the presented ViewController preferredContentSize or fixed at UIPopoverPresentationControllerDelegate's 
```
popoverPresentationController(_ popoverPresentationController: UIPopoverPresentationController, willRepositionPopoverTo rect: UnsafeMutablePointer<CGRect>, in view: AutoreleasingUnsafeMutablePointer<UIView>)
```

**Comment by jessesquires** [comment]
Thanks @blackchena ! 😄 

Can you clarify what you're asking? I'm not sure I understand.

**Comment by blackchena** [comment]
I want to changed presented viewController's frame when I use .popover type
